<a href="https://colab.research.google.com/github/Joshua-Bowden-Curtin/ISYS2001-Redo/blob/main/testing_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [38]:
# Load a CSV file into a DataFrame (think "smart spreadsheet")
df = pd.read_csv('transactions.csv')
print(df)

   transaction_id product  quantity  price        date
0               1   Apple         2    1.0  2023-01-01
1               2  Banana         3    0.5  2023-01-01
2               3  Orange         1    1.2  2023-01-02
3               4   Apple         1    1.0  2023-01-03
4               5   Mango         4    0.8  2023-01-03

It looks like the `transactions.csv` file was not found. To help you proceed, I'm creating a dummy `transactions.csv` file with some sample data. If you have your own `transactions.csv`, you can upload it to your Colab environment by clicking the folder icon on the left sidebar and then the 'Upload to session storage' icon.

In [ ]:
import pandas as pd

# Create a dummy DataFrame
dummy_data = {
    'transaction_id': [1, 2, 3, 4, 5],
    'product': ['Apple', 'Banana', 'Orange', 'Apple', 'Mango'],
    'quantity': [2, 3, 1, 1, 4],
    'price': [1.0, 0.5, 1.2, 1.0, 0.8],
    'date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-03', '2023-01-03']
}
dummy_df = pd.DataFrame(dummy_data)

# Save the dummy DataFrame to a CSV file named 'transactions.csv'
dummy_df.to_csv('transactions.csv', index=False)

print("Dummy 'transactions.csv' created successfully!")

Dummy 'transactions.csv' created successfully!

In [39]:


df.head()

   transaction_id product  quantity  price        date
0               1   Apple         2    1.0  2023-01-01
1               2  Banana         3    0.5  2023-01-01
2               3  Orange         1    1.2  2023-01-02
3               4   Apple         1    1.0  2023-01-03
4               5   Mango         4    0.8  2023-01-03

In [ ]:
while True:
    print("\nSelect an option to view information about the DataFrame:")
    print("1 - Display df.head()")
    print("2 - Display df.info()")
    print("3 - Display df.columns")
    print("4 - Display df.describe()")
    print("0 - Exit menu")

    user_choice = input("Enter your choice (1, 2, 3, 4, or 0 to exit): ")

    if user_choice == '1':
        print("\n--- df.head() ---")
        display(df.head())
    elif user_choice == '2':
        print("\n--- df.info() ---")
        df.info()
    elif user_choice == '3':
        print("\n--- df.columns ---")
        display(df.columns)
    elif user_choice == '4':
        print("\n--- df.describe() ---")
        display(df.describe())
    elif user_choice == '0':
        print("Exiting menu. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter 1, 2, 3, or 4.")

Select an option to view information about the DataFrame:
1 - Display df.head()
2 - Display df.info()
3 - Display df.columns
4 - Display df.describe()
0 - Exit menu
Enter your choice (1, 2, 3, 4, or 0 to exit): 2

--- df.info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  5 non-null      int64
 1   product         5 non-null      object
 2   quantity        5 non-null      int64
 3   price           5 non-null      float64
 4   date            5 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

Select an option to view information about the DataFrame:
1 - Display df.head()
2 - Display df.info()
3 - Display df.columns
4 - Display df.describe()
0 - Exit menu
Enter your choice (1, 2, 3, 4, or 0 to exit): 4

--- df.describe() ---

       transaction_id  quantity     price
count        5.000000   5.00000  5.000000
mean         3.000000   2.20000  0.900000
std          1.581139   1.30384  0.264575
min          1.000000   1.00000  0.500000
25%          2.000000   1.00000  0.800000
50%          3.000000   2.00000  1.000000
75%          4.000000   3.00000  1.000000
max          5.000000   4.00000  1.200000

Select an option to view information about the DataFrame:
1 - Display df.head()
2 - Display df.info()
3 - Display df.columns
4 - Display df.describe()
0 - Exit menu
Enter your choice (1, 2, 3, 4, or 0 to exit): 1

--- df.head() ---

   transaction_id product  quantity  price        date
0               1   Apple         2    1.0  2023-01-01
1               2  Banana         3    0.5  2023-01-01
2               3  Orange         1    1.2  2023-01-02
3               4   Apple         1    1.0  2023-01-03
4               5   Mango         4    0.8  2023-01-03

Select an option to view information about the DataFrame:
1 - Display df.head()
2 - Display df.info()
3 - Display df.columns
4 - Display df.describe()
0 - Exit menu
Enter your choice (1, 2, 3, 4, or 0 to exit): 0
Exiting menu. Goodbye!

Relating to the above:

When user choice == a value, have the code direct to a specific block relevant to the function being run and when that function concludes have it return to the main block.

In [40]:
# Count values in a category
df['product'].value_counts()


#---

# Filter data
quantity = df[df['product'] == 'Quantity']


#---

# Group and summarize
df.groupby('product')['quantity'].sum()

product
Apple     3
Banana    3
Mango     4
Orange    1
Name: quantity, dtype: int64